[project]
name = "gitty_mix"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.10"',
    "PyGithub"
]
exclude = ["accounts_local.json"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project.scripts]
gix = "gix.gix:main"
